[package]
name = "lattice-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
lattice-protocol = { path = "../lattice-protocol" }
ropey = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[lints]
workspace = true
