(class_declaration) @fold
(interface_declaration) @fold
(enum_declaration) @fold
(method_declaration) @fold
(constructor_declaration) @fold
(block) @fold
(if_statement) @fold
(for_statement) @fold
(while_statement) @fold
(try_statement) @fold
  (switch_expression) @fold
