(function_declaration) @fold
(method_declaration) @fold
(type_declaration) @fold
(block) @fold
(composite_literal) @fold
(if_statement) @fold
(for_statement) @fold
  (expression_switch_statement) @fold
  (type_switch_statement) @fold
(select_statement) @fold
