[package]
name = "lattice-syntax"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
tree-sitter = { workspace = true }
tree-sitter-highlight = { workspace = true }
streaming-iterator = { workspace = true }
tree-sitter-rust = { workspace = true }
tree-sitter-python = { workspace = true }
tree-sitter-javascript = { workspace = true }
tree-sitter-md = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
