//! Build script: discover every user doc under `docs/user/` and emit
//! a generated `HELP_TOPICS` table that `topics.rs` includes. This
//! replaces the hand-written per-file `include_str!` + `register`
//! boilerplate — drop a `.md` into `docs/user/` and it becomes a
//! `:help` topic automatically.
//!
//! Each doc self-describes its registry metadata through an optional
//! leading YAML frontmatter block (the Hugo / Jekyll convention — a
//! `---` fence at the very top), which is stripped here before the
//! body is embedded so it never renders in `:help`:
//!
//! ```text
//! ---
//! summary: One-line summary shown in the `:help` index.
//! related: [fold, foldmethod]
//! ---
//! # Folding
//! ...
//! ```
//!
//! `related` accepts an inline list (`[a, b]`) or a bare
//! comma-separated value (`a, b`).
//!
//! `summary` is the index/completion blurb; `related` is the
//! comma-separated list of command-name substrings that
//! `:describe-command` matches to emit "See also" cross-links. A
//! doc with no frontmatter still registers — its summary is derived
//! from the first heading and it carries no command patterns.
//!
//! The bodies are embedded as string literals in the generated file,
//! so the binary stays self-contained (no runtime filesystem
//! dependency), exactly as the previous `include_str!` approach did.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    // `docs/user` is two levels up from `crates/lattice-help`.
    let docs_root = PathBuf::from(&manifest).join("../../docs/user");
    let docs_root = docs_root
        .canonicalize()
        .unwrap_or_else(|e| panic!("docs/user not found at {}: {e}", docs_root.display()));

    // Rebuild when any doc is added / edited / removed.
    println!("cargo:rerun-if-changed={}", docs_root.display());

    let mut topics: Vec<Topic> = Vec::new();
    collect(&docs_root, &mut topics);

    // Deterministic order: the index first, then alphabetical by
    // name. The registry preserves registration order for the
    // `:help` index listing.
    topics.sort_by(|a, b| {
        let rank = |n: &str| if n == "index" { 0 } else { 1 };
        rank(&a.name)
            .cmp(&rank(&b.name))
            .then_with(|| a.name.cmp(&b.name))
    });

    let mut out = String::from(
        "// @generated by build.rs — do not edit. Source: docs/user/**/*.md\n\
         static HELP_TOPICS: &[(&str, &str, &[&str], &str)] = &[\n",
    );
    for t in &topics {
        let related = t
            .related
            .iter()
            .map(|r| format!("{r:?}"))
            .collect::<Vec<_>>()
            .join(", ");
        // `{:?}` renders each string as a valid, fully-escaped Rust
        // string literal — no raw-string delimiter-collision risk.
        out.push_str(&format!(
            "    ({:?}, {:?}, &[{}], {:?}),\n",
            t.name, t.summary, related, t.body
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("help_topics.rs");
    fs::write(&dest, out).expect("write generated help_topics.rs");
}

struct Topic {
    name: String,
    summary: String,
    related: Vec<String>,
    body: String,
}

/// Recursively collect `*.md` docs, skipping the `tutor/` subtree
/// (the tutor lessons are a separate surface owned by `lattice-host`,
/// not `:help` topics).
fn collect(dir: &Path, out: &mut Vec<Topic>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if path.file_name().and_then(|n| n.to_str()) == Some("tutor") {
                continue;
            }
            collect(&path, out);
        } else if path.extension().and_then(|e| e.to_str()) == Some("md") {
            println!("cargo:rerun-if-changed={}", path.display());
            let raw = fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
            let stem = path
                .file_stem()
                .and_then(|s| s.to_str())
                .unwrap_or("untitled");
            // `README.md` is the index page reached by bare `:help`.
            let name = if stem == "README" {
                "index".to_string()
            } else {
                stem.to_string()
            };
            let (summary, related, body) = parse_frontmatter(&raw);
            let summary = if summary.is_empty() {
                derive_summary(&body)
            } else {
                summary
            };
            out.push(Topic {
                name,
                summary,
                related,
                body,
            });
        }
    }
}

/// Parse a leading `---` YAML frontmatter fence (Hugo / Jekyll
/// convention), returning `(summary, related,
/// body-without-frontmatter)`. When there is no frontmatter,
/// returns an empty summary + no patterns + the body verbatim (the
/// caller derives a summary).
fn parse_frontmatter(raw: &str) -> (String, Vec<String>, String) {
    let trimmed = raw.trim_start_matches(['\u{feff}', '\n', '\r', ' ', '\t']);
    // The opening fence must be a `---` line at the very top.
    if !(trimmed.starts_with("---\n") || trimmed.starts_with("---\r\n")) {
        return (String::new(), Vec::new(), raw.to_string());
    }
    let mut lines = trimmed.lines();
    let _open = lines.next(); // the opening `---`

    let mut summary = String::new();
    let mut related = Vec::new();
    let mut closed = false;
    for line in lines.by_ref() {
        if line.trim_end() == "---" {
            closed = true;
            break;
        }
        let line = line.trim();
        if let Some(v) = line.strip_prefix("summary:") {
            summary = unquote(v.trim());
        } else if let Some(v) = line.strip_prefix("related:") {
            related = parse_list(v);
        }
    }
    // No closing fence ⇒ not real frontmatter; keep the body as-is.
    if !closed {
        return (String::new(), Vec::new(), raw.to_string());
    }
    let body = lines
        .collect::<Vec<_>>()
        .join("\n")
        .trim_start_matches(['\n', '\r'])
        .to_string();
    (summary, related, body)
}

/// Parse a YAML-ish list value: inline `[a, b]` or bare `a, b`.
fn parse_list(v: &str) -> Vec<String> {
    let v = v.trim();
    let inner = v
        .strip_prefix('[')
        .and_then(|s| s.strip_suffix(']'))
        .unwrap_or(v);
    inner
        .split(',')
        .map(|t| unquote(t.trim()))
        .filter(|t| !t.is_empty())
        .collect()
}

/// Strip a single layer of matching single / double quotes.
fn unquote(s: &str) -> String {
    let s = s.trim();
    for q in ['"', '\''] {
        if s.len() >= 2 && s.starts_with(q) && s.ends_with(q) {
            return s[1..s.len() - 1].to_string();
        }
    }
    s.to_string()
}

/// Fallback summary for a doc without frontmatter: the text of the
/// first `# ` heading, else the first non-empty line, truncated.
fn derive_summary(body: &str) -> String {
    for line in body.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let text = line.trim_start_matches('#').trim();
        if !text.is_empty() {
            return text.chars().take(120).collect();
        }
    }
    String::new()
}
