[package]
name = "lattice-ui-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
lattice-protocol = { path = "../lattice-protocol" }
lattice-core = { path = "../lattice-core" }
lattice-grammar = { path = "../lattice-grammar" }
lattice-completion = { path = "../lattice-completion" }
lattice-syntax = { path = "../lattice-syntax" }
lattice-runtime = { path = "../lattice-runtime" }
fancy-regex = { workspace = true }
ratatui = { workspace = true }
crossterm = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
