//! PI.6: rendering the plugin-API catalog for humans.
//!
//! Moved out of the host at PI.6. It renders the CATALOG, which is this
//! crate's, and the move is what lets the site's reference page be generated
//! by a test here rather than only by `:export-plugin-api` in a running
//! editor.

use crate::{Capability, Direction};

pub fn direction_prose(d: Direction) -> &'static str {
    match d {
        Direction::GuestExport => "guest implements this interface",
        Direction::GuestImport => "guest calls into the host through it",
        Direction::Both => "guest both implements and calls it",
        Direction::TypesOnly => "shared types only (not called directly)",
    }
}

pub fn direction_short(d: Direction) -> &'static str {
    match d {
        Direction::GuestExport => "exports",
        Direction::GuestImport => "imports",
        Direction::Both => "both",
        Direction::TypesOnly => "types",
    }
}

pub fn capability_prose(c: Capability) -> &'static str {
    match c {
        Capability::Fs => "filesystem",
        Capability::Net => "network",
        Capability::Proc => "subprocess",
        Capability::None => "none (pure data / dispatch)",
    }
}

pub fn capability_short(c: Capability) -> &'static str {
    match c {
        Capability::Fs => "fs",
        Capability::Net => "net",
        Capability::Proc => "proc",
        Capability::None => "-",
    }
}

/// PI.6: the whole plugin API as markdown, rendered from the canonical `wit/`
/// package.
///
/// Lives here rather than in the host because it is a rendering of the
/// CATALOG, and the catalog is this crate's. That placement is what lets the
/// site's reference page be generated by a test in this crate instead of only
/// by `:export-plugin-api` inside a running editor — a reference a developer
/// can only obtain by launching the editor is one they will not read.
pub fn markdown() -> String {
    let cat = crate::catalog();
    let mut out = String::new();
    out.push_str("# Lattice Plugin API\n\n");
    out.push_str(&format!(
        "Derived from the canonical `wit/` package — {} seam(s).\n",
        cat.interfaces.len()
    ));
    for iface in &cat.interfaces {
        out.push_str(&format!(
            "\n## {}  ({}, capability: {})\n\n",
            iface.name,
            direction_prose(iface.direction),
            capability_prose(iface.capability),
        ));
        if let Some(doc) = &iface.doc {
            out.push_str(doc);
            out.push_str("\n\n");
        }
        out.push_str(&format!("### Functions ({})\n\n", iface.functions.len()));
        if iface.functions.is_empty() {
            out.push_str("_(none — a shared type interface)_\n");
        } else {
            for f in &iface.functions {
                let first = f
                    .doc
                    .as_deref()
                    .and_then(|d| d.lines().next())
                    .unwrap_or("");
                out.push_str(&format!("- `{}` — {first}\n", f.name));
            }
        }
    }
    out
}
