[package]
name = "lattice-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
lattice-protocol = { path = "../lattice-protocol" }
lattice-core = { path = "../lattice-core" }
lattice-grammar = { path = "../lattice-grammar" }
tokio = { workspace = true }
arc-swap = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "time"] }
criterion = { workspace = true }
linkme = { workspace = true }

[[bench]]
name = "actor"
harness = false

[lints]
workspace = true
