// `linkme`'s distributed slices use `link_section` to
// aggregate items at link time. Workspace lints `deny`
// `unsafe_code` (CLAUDE.md), so we opt this module in --
// the safety argument is that linkme is the standard Rust
// solution for cross-crate aggregation, the link-section
// usage is contained to its own machinery, and no raw
// pointer / unchecked-cast code lives here.
#![allow(unsafe_code)]

//! Option groups: the user-facing organization unit for
//! `:customize <name>` (`mode-architecture.md` §6.7.1.1).
//!
//! Each group is a unique Rust type implementing [`OptionGroup`].
//! Pre-registered built-in groups ship with the editor:
//! `Editor`, `Display`, `Editing`, `Lsp`, `Completion`, `Picker`,
//! `Filetree`, `Oil`, `Help`, `Appearance`. Plugins can join
//! existing groups (by referencing the type) or declare new
//! ones (in their own `<plugin-id>.<group>` namespace).
//!
//! Compile-time invariants enforced by the [`crate::groups!`]
//! macro:
//!
//! - Group display names cannot end in `-mode`. The
//!   modes-vs-groups disambiguation rule
//!   (`mode-architecture.md` §6.7.1) depends on this -- a name
//!   ending in `-mode` is a mode; a name not ending in `-mode`
//!   is a group. The macro emits a `const fn` byte-walk
//!   assertion at the declaration site; violations are compile
//!   errors.
//! - Within a crate, two `groups!` invocations with the same
//!   identifier are duplicate `struct` definitions ⇒ compile
//!   error.
//!
//! Cross-crate display-name uniqueness is enforced at startup
//! via [`linkme`] aggregation in [`GROUP_DECLS`].

use std::any::TypeId;

/// Compile-time declaration of one option group. Each group
/// is a unit struct (typically generated by the [`crate::groups!`]
/// macro) implementing this trait.
pub trait OptionGroup: 'static {
    /// Public display name. Used as the boundary string for
    /// `:customize <name>` and as the prefix-match key for
    /// option group queries. Cannot end in `-mode`.
    const NAME: &'static str;

    /// Doc string. Shown in `:describe-group <name>` and the
    /// `:customize` group picker.
    const DOC: &'static str;

    /// `TypeId` for type-driven group lookups.
    fn type_id() -> TypeId
    where
        Self: Sized,
    {
        TypeId::of::<Self>()
    }
}

/// Metadata captured at macro expansion for one group. Submitted
/// to the [`GROUP_DECLS`] distributed slice; the registry's
/// startup loader walks the slice to validate uniqueness and
/// build the `&str → TypeId` lookup table.
pub struct OptionGroupMetadata {
    pub name: &'static str,
    pub doc: &'static str,
    pub type_id: fn() -> TypeId,
}

impl OptionGroupMetadata {
    pub const fn for_group<G: OptionGroup>() -> Self {
        Self {
            name: G::NAME,
            doc: G::DOC,
            type_id: TypeId::of::<G>,
        }
    }
}

/// Distributed slice of every group declared anywhere in the
/// workspace. Each `groups!` macro invocation submits a
/// `&'static OptionGroupMetadata` element here. The registry
/// validates cross-crate uniqueness at startup.
#[linkme::distributed_slice]
pub static GROUP_DECLS: [&'static OptionGroupMetadata];

/// `const fn` byte-walk: returns true iff `s` ends in the
/// literal suffix `-mode`. Used by the `groups!` macro to
/// assert the disambiguation invariant at compile time.
///
/// Returns `false` for strings shorter than the suffix.
/// Implementation walks bytes from the end -- ASCII-safe
/// because mode/group names are constrained to lowercase
/// letters, digits, and hyphens.
pub const fn ends_with_mode_suffix(s: &str) -> bool {
    let bytes = s.as_bytes();
    let suffix = b"-mode";
    let n = bytes.len();
    let m = suffix.len();
    if n < m {
        return false;
    }
    let mut i = 0;
    while i < m {
        if bytes[n - m + i] != suffix[i] {
            return false;
        }
        i += 1;
    }
    true
}

// ---------------------------------------------------------
// Pre-registered built-in groups.
// ---------------------------------------------------------

/// Built-in editor options without a mode-specific prefix
/// (`tabstop`, `number`, `wrap`, ...). Reserved namespace --
/// only built-in modes can declare options into this group
/// (enforced by the macro API surface, not by group access
/// control; see `mode-architecture.md` §6.8 for the
/// reservation mechanism).
pub struct Editor;
impl OptionGroup for Editor {
    const NAME: &'static str = "editor";
    const DOC: &'static str = "Bare-named editor options (tabstop, number, wrap, foldmethod, ...). \
         Reserved namespace -- plugins must use their own prefix.";
}

/// Visual-presentation options across modes: line numbers, wrap
/// continuation marker, gutter contents, current-line highlight,
/// whitespace visualization.
pub struct Display;
impl OptionGroup for Display {
    const NAME: &'static str = "display";
    const DOC: &'static str = "Visual-presentation options across modes \
         (line numbers, wrap, whitespace visualization, ...).";
}

/// Editing-related options: search behavior, indent, auto-pair,
/// and similar text-manipulation defaults.
pub struct Editing;
impl OptionGroup for Editing {
    const NAME: &'static str = "editing";
    const DOC: &'static str = "Editing-related options (search, indent, auto-pair, ...).";
}

/// LSP umbrella group: collects every option owned by an LSP
/// mode (`lsp-mode`, `lsp-completion-mode`, `lsp-diagnostics-mode`,
/// ...). `:customize lsp` shows the union.
pub struct Lsp;
impl OptionGroup for Lsp {
    const NAME: &'static str = "lsp";
    const DOC: &'static str = "Every option owned by an LSP mode. \
         `:customize lsp` shows the union sectioned by owning mode.";
}

/// Completion-related options across providers (LSP completion,
/// snippets, buffer-words, paths).
pub struct Completion;
impl OptionGroup for Completion {
    const NAME: &'static str = "completion";
    const DOC: &'static str =
        "Completion options across providers (LSP, snippets, buffer-words, paths).";
}

/// Picker (file finder, command palette, symbol search) options.
pub struct Picker;
impl OptionGroup for Picker {
    const NAME: &'static str = "picker";
    const DOC: &'static str = "File finder, command palette, symbol search.";
}

/// File-tree mode options.
pub struct Filetree;
impl OptionGroup for Filetree {
    const NAME: &'static str = "filetree";
    const DOC: &'static str = "File tree navigation buffer.";
}

/// Oil mode (editable directory buffer) options.
pub struct Oil;
impl OptionGroup for Oil {
    const NAME: &'static str = "oil";
    const DOC: &'static str = "Oil-style editable directory buffer.";
}

/// Help / documentation buffer options.
pub struct Help;
impl OptionGroup for Help {
    const NAME: &'static str = "help";
    const DOC: &'static str = "Help / documentation buffers.";
}

/// Appearance / theming options (colors, sprite icons, font
/// rendering).
pub struct Appearance;
impl OptionGroup for Appearance {
    const NAME: &'static str = "appearance";
    const DOC: &'static str =
        "Appearance / theming options (colors, sprite icons, font rendering).";
}

/// `*messages*` audit-log buffer + tracing-bridge options.
pub struct Messages;
impl OptionGroup for Messages {
    const NAME: &'static str = "messages";
    const DOC: &'static str = "Echo-area + `*messages*` buffer + tracing bridge.";
}

/// Tabline (tab strip at the top of the screen). Issue #29
/// (2026-05-22).
pub struct Tabline;
impl OptionGroup for Tabline {
    const NAME: &'static str = "tabline";
    const DOC: &'static str = "Tabline (vim-style tab strip).";
}

/// Terminal-mode (PTY-backed shell buffer) options. Added with
/// T2.b.0 (`terminal.esc-exits`); T2.b/T4 grow the group with
/// `terminal.shell`, `terminal.scrollback-lines`, etc.
pub struct Terminal;
impl OptionGroup for Terminal {
    const NAME: &'static str = "terminal";
    const DOC: &'static str = "PTY-backed terminal buffer.";
}

/// Project-search options (`:search`, project-search multibuffer,
/// future LSP-references etc. as those settle). K.4.6 follow-up
/// (2026-06-02): `search.context_size` added by
/// `ProjectSearchMode` in `lattice-multibuffer`.
pub struct Search;
impl OptionGroup for Search {
    const NAME: &'static str = "search";
    const DOC: &'static str =
        "Project-search options: `:search` clustering, context lines, scan limits.";
}

/// Snippet-engine options. SN.3b (2026-06-14): `snippet.activation`
/// + `snippet.languages` are declared by `SnippetMode` in
/// `lattice-snippet`; this group is the customize/listing umbrella
/// (`:customize snippet`). Same shape as `Search` above — group
/// here, options in the owning mode's crate.
pub struct Snippet;
impl OptionGroup for Snippet {
    const NAME: &'static str = "snippet";
    const DOC: &'static str = "Snippet engine: activation policy + supported-language allowlist.";
}

/// Modeline (bottom per-pane status row) layout options. ML.5
/// (2026-06-21): `ui.modeline.{left,center,right}` zone assignment +
/// `ui.modeline.separator`. The `:customize modeline` umbrella for the
/// configurable element-system modeline
/// (`docs/dev/architecture/modeline.md` §11).
pub struct Modeline;
impl OptionGroup for Modeline {
    const NAME: &'static str = "modeline";
    const DOC: &'static str =
        "Modeline (bottom per-pane status row): per-zone element layout + separator.";
}

/// Diagnostics presentation options. L4 (2026-06-21):
/// `ui.diagnostics.inline` + `ui.diagnostics.inline-min-severity` drive
/// the inline end-of-line diagnostic summary (`lsp-architecture.md`
/// §15). The `:customize diagnostics` umbrella.
pub struct Diagnostics;
impl OptionGroup for Diagnostics {
    const NAME: &'static str = "diagnostics";
    const DOC: &'static str =
        "Diagnostics presentation: inline end-of-line summary scope + min-severity.";
}

/// Plugin observability options: `plugin.trace-level` (the global default
/// boundary-trace verbosity the host's `PluginTracer` gates on). PO.4.3.
pub struct Plugin;
impl OptionGroup for Plugin {
    const NAME: &'static str = "plugin";
    const DOC: &'static str = "Plugin observability: the global default boundary-trace verbosity.";
}

/// GPUI window options: OS chrome (`ui.window.decorations`) and
/// maximize-on-launch (`ui.window.start-maximized`). GPUI peer only.
pub struct Window;
impl OptionGroup for Window {
    const NAME: &'static str = "window";
    const DOC: &'static str =
        "GPUI window options (borderless chrome, maximize on launch). GPUI peer only.";
}

/// AI-agent (ACP client) options. AI-1b: `ai.log` / `ai.log_level`
/// gate/seed the per-process `AiLogger` log rings (mirroring the LSP
/// log group above). Boot-time wiring into an `AiLogger` lands in a
/// later task; this group only makes the options resolvable and
/// `:set`-able.
pub struct Ai;
impl OptionGroup for Ai {
    const NAME: &'static str = "ai";
    const DOC: &'static str = "AI-agent (ACP client) options: per-process log capture + level.";
}

// linkme submissions for the built-in groups.
// Each submission registers one group's metadata; the registry's
// startup loader walks GROUP_DECLS and panics on duplicate names.
//
// The `static` items are `pub` so cross-crate consumers can also
// reference the group types directly (the metadata is internal to
// linkme aggregation).

#[linkme::distributed_slice(GROUP_DECLS)]
static EDITOR_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Editor>();

#[linkme::distributed_slice(GROUP_DECLS)]
static DISPLAY_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Display>();

#[linkme::distributed_slice(GROUP_DECLS)]
static EDITING_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Editing>();

#[linkme::distributed_slice(GROUP_DECLS)]
static LSP_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Lsp>();

#[linkme::distributed_slice(GROUP_DECLS)]
static COMPLETION_GROUP_LINK: &OptionGroupMetadata =
    &OptionGroupMetadata::for_group::<Completion>();

#[linkme::distributed_slice(GROUP_DECLS)]
static PICKER_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Picker>();

#[linkme::distributed_slice(GROUP_DECLS)]
static FILETREE_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Filetree>();

#[linkme::distributed_slice(GROUP_DECLS)]
static OIL_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Oil>();

#[linkme::distributed_slice(GROUP_DECLS)]
static HELP_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Help>();

#[linkme::distributed_slice(GROUP_DECLS)]
static APPEARANCE_GROUP_LINK: &OptionGroupMetadata =
    &OptionGroupMetadata::for_group::<Appearance>();

#[linkme::distributed_slice(GROUP_DECLS)]
static MESSAGES_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Messages>();

#[linkme::distributed_slice(GROUP_DECLS)]
static TABLINE_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Tabline>();

#[linkme::distributed_slice(GROUP_DECLS)]
static TERMINAL_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Terminal>();

#[linkme::distributed_slice(GROUP_DECLS)]
static SEARCH_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Search>();

#[linkme::distributed_slice(GROUP_DECLS)]
static SNIPPET_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Snippet>();

#[linkme::distributed_slice(GROUP_DECLS)]
static MODELINE_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Modeline>();

#[linkme::distributed_slice(GROUP_DECLS)]
static DIAGNOSTICS_GROUP_LINK: &OptionGroupMetadata =
    &OptionGroupMetadata::for_group::<Diagnostics>();

#[linkme::distributed_slice(GROUP_DECLS)]
static WINDOW_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Window>();

#[linkme::distributed_slice(GROUP_DECLS)]
static AI_GROUP_LINK: &OptionGroupMetadata = &OptionGroupMetadata::for_group::<Ai>();

// Compile-time naming-rule assertions for the built-in groups.
// Verifies the `groups!` macro convention even though these
// groups are hand-written: no built-in group's name ends in
// `-mode`. If we add a `groups!` macro that wraps these
// later, it'll emit the same assertion at the macro call site.

const _: () = {
    assert!(!ends_with_mode_suffix(Editor::NAME));
    assert!(!ends_with_mode_suffix(Display::NAME));
    assert!(!ends_with_mode_suffix(Editing::NAME));
    assert!(!ends_with_mode_suffix(Lsp::NAME));
    assert!(!ends_with_mode_suffix(Completion::NAME));
    assert!(!ends_with_mode_suffix(Picker::NAME));
    assert!(!ends_with_mode_suffix(Filetree::NAME));
    assert!(!ends_with_mode_suffix(Oil::NAME));
    assert!(!ends_with_mode_suffix(Help::NAME));
    assert!(!ends_with_mode_suffix(Appearance::NAME));
    assert!(!ends_with_mode_suffix(Terminal::NAME));
    assert!(!ends_with_mode_suffix(Search::NAME));
    assert!(!ends_with_mode_suffix(Snippet::NAME));
    assert!(!ends_with_mode_suffix(Modeline::NAME));
    assert!(!ends_with_mode_suffix(Diagnostics::NAME));
    assert!(!ends_with_mode_suffix(Window::NAME));
    assert!(!ends_with_mode_suffix(Ai::NAME));
};

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ends_with_mode_suffix_positive() {
        assert!(ends_with_mode_suffix("rust-mode"));
        assert!(ends_with_mode_suffix("lsp-completion-mode"));
        assert!(ends_with_mode_suffix("a-mode"));
        assert!(ends_with_mode_suffix("-mode"));
    }

    #[test]
    fn ends_with_mode_suffix_negative() {
        assert!(!ends_with_mode_suffix("editor"));
        assert!(!ends_with_mode_suffix("lsp"));
        assert!(!ends_with_mode_suffix("mode"));
        assert!(!ends_with_mode_suffix("modal"));
        assert!(!ends_with_mode_suffix(""));
        assert!(!ends_with_mode_suffix("foo"));
    }

    #[test]
    fn builtin_groups_have_distinct_type_ids() {
        // Trivially true (Rust types are unique by path), but
        // pinning the invariant catches any accidental shared
        // alias / re-export collapse.
        let editor = Editor::type_id();
        let display = Display::type_id();
        assert_ne!(editor, display);
    }

    #[test]
    fn linkme_aggregates_builtin_groups() {
        // Walk the slice and confirm every built-in name shows up.
        let names: Vec<_> = GROUP_DECLS.iter().map(|g| g.name).collect();
        for expected in [
            "editor",
            "display",
            "editing",
            "lsp",
            "completion",
            "picker",
            "filetree",
            "oil",
            "help",
            "appearance",
        ] {
            assert!(
                names.contains(&expected),
                "linkme slice missing group: {expected}; saw {names:?}"
            );
        }
    }

    #[test]
    fn no_duplicate_group_names_in_slice() {
        let mut names: Vec<&str> = GROUP_DECLS.iter().map(|g| g.name).collect();
        names.sort_unstable();
        let before = names.len();
        names.dedup();
        assert_eq!(
            names.len(),
            before,
            "duplicate group display name in linkme slice",
        );
    }
}
