[package]
name = "lattice-mode"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
internment = { workspace = true }
bitflags = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }
lattice-protocol = { path = "../lattice-protocol" }

[lints]
workspace = true
